name: Image Optimization and Deployment

on:
  push:
    branches:
      - main
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'

permissions: write-all

jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop Workflow if AQI is greater than 2
        id: check-condition
        run: |
          node scripts/stopWorkflow.js 
          echo ::set-output name=stopWorkflow::$(node -e "console.log(shouldStopWorkflow())")

      - name: Build and Push to gh-pages branch
        if: steps.check-condition.outputs.stopWorkflow == 'false' && [ "${{ github.event_name }}" == "schedule" ]
        run: |
          yarn install 
          run: yarn build
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Workflow Run: Generate Compressed Images"
          git push -u -f origin gh-pages

