name: Build Overbrowsing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all
jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/build/stopWorkflow.js

      - name: Set Stop Workflow Output
        id: set-stop-output
        run: echo "stopWorkflow=${{ steps.stop-check.outputs.stopWorkflow }}" > stopWorkflow.env

      - name: Set Stop Workflow Environment Variable
        run: echo "STOP_WORKFLOW=$(cat stopWorkflow.env)" >> $GITHUB_ENV

      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          yarn install
          yarn build

          mv _site/* .
          mv _site/.git .git
          rm -rf _site
          git add .
          git commit -m "Update gh-pages with _site contents"
          git branch -M gh-pages
          git push -u -f origin gh-pages