name: Build Overbrowsing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all
jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/build/stopWorkflow.js

      - name: Set Stop Workflow Output
        id: set-stop-output
        run: echo "stopWorkflow=${{ steps.stop-check.outputs.stopWorkflow }}" > stopWorkflow.env

      - name: Set Stop Workflow Environment Variable
        run: echo "STOP_WORKFLOW=$(cat stopWorkflow.env)" >> $GITHUB_ENV

      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
              ref: gh-pages # This checks out the gh-pages branch
      
            - name: Copy contents from _site
              run: rsync -av --delete ../main/_site/ ./
      
            - name: Commit and push changes
              run: |
                git add -A
                git commit -m "Update gh-pages with _site contents"
                git push origin gh-pages
      
