name: Image Optimization and Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */2 * *'

permissions: write-all

jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove cache
        run: |
          rm -rf cache
          mkdir cache
          mkdir cache/images

      - name: Install GraphicsMagick
        run: sudo apt-get install graphicsmagick -y

      - name: Install dependencies
        run: |
          yarn install

      - name: Run Yarn Build
        run: yarn build

      - name: Commit and push optimized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git checkout gh-pages
          git add .
          git commit -m "Workflow Run: Generate Compressed Images"
          git push -u -f origin gh-pages