name: Build Overbrowsing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all
jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/build/stopWorkflow.js

      - name: Set Stop Workflow Output
        id: set-stop-output
        run: echo "stopWorkflow=${{ steps.stop-check.outputs.stopWorkflow }}" > stopWorkflow.env

      - name: Set Stop Workflow Environment Variable
        run: echo "STOP_WORKFLOW=$(cat stopWorkflow.env)" >> $GITHUB_ENV

      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          yarn install
          yarn build

      - name: Deploy to gh-pages
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          # Create a temporary directory to clone the repository
          mkdir deploy
          cd deploy

          # Clone the repository
          git clone https://github.com/${{ github.repository }}

          # Move into the repository directory
          cd <your-repository-name>

          # Switch to the gh-pages branch
          git checkout gh-pages

          # Clear existing contents
          rm -rf *

          # Copy contents from _site
          cp -r ../_site/* .

          # Add, commit, and push changes
          git add .
          git commit -m "Update gh-pages with latest build"
          git push origin gh-pages

      - name: Clean up
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          cd ..
          rm -rf deploy