name: Image Optimization and Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */2 * *'

permissions: write-all

jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update -y && sudo apt-get install -y imagemagick

      - name: Run Yarn Build
        run: yarn build

      - name: Optimize and Convert to Black & White with Dithering
        run: |
          for file in uploads/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              extension="${filename##*.}"
              filename="${filename%.*}"
              output_file="uploads/$filename.png"
              convert "$file" -type Grayscale -ordered-dither h4x4a -quality 100% "$output_file"
            fi
          done

      - name: Commit and push optimized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add uploads
          git commit -m "Workflow Run: Generate Compressed Images"
          git checkout -b gh-pages
          git push -u -f origin gh-pages
