name: Image Optimization and Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all

jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch API Data
        run: |
          API_DATA=$(curl -s "https://api.websitecarbon.com/site?url=https://overbrowsing.com")
          # Create or update the carbon-data.json file
          echo "$API_DATA" > cache/carbon-data.json
        continue-on-error: true

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/stopWorkflow.js
        continue-on-error: true

      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || steps.stop-check.outcome != 'failure' }}
        run: |
          yarn install
          yarn build

          # Copy the fetched API data to your build directory
          cp api_data.json dist/api_data.json

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Workflow Run: Generate Compressed Images"
          git push -u -f origin gh-pages
