name: Build Overbrowsing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all
jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/build/stopWorkflow.js

      - name: Set Stop Workflow Output
        id: set-stop-output
        run: echo "stopWorkflow=${{ steps.stop-check.outputs.stopWorkflow }}" > stopWorkflow.env

      - name: Set Stop Workflow Environment Variable
        run: echo "STOP_WORKFLOW=$(cat stopWorkflow.env)" >> $GITHUB_ENV

      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          yarn install
          yarn build

      - name: Deploy to gh-pages
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

          # Check if gh-pages branch exists
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout -b gh-pages
          fi

          # Handle local modifications
          git add -u
          git reset --hard

          git merge main

          # Remove existing files in the branch
          # find . -maxdepth 1 ! -name '_site' ! -name '.' ! -name '..' -exec rm -r {} \;

          # Move all contents of _site to the root
          mv _site/* .

          # Delete the _site folder
          rm -r _site

          git add .
          git commit -m "Workflow Run: Generate Compressed Images"
          git push -u -f origin gh-pages