name: Build Overbrowsing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all
jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/build/stopWorkflow.js

      - name: Set Stop Workflow Output
        id: set-stop-output
        run: echo "stopWorkflow=${{ steps.stop-check.outputs.stopWorkflow }}" > stopWorkflow.env

      - name: Set Stop Workflow Environment Variable
        run: echo "STOP_WORKFLOW=$(cat stopWorkflow.env)" >> $GITHUB_ENV

      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          yarn install
          yarn build

          # Create a temporary directory
          mkdir temp

          # Move the contents of _site to the temp directory
          mv _site/* temp/

          # Remove everything from the working directory
          rm -rf *

          # Move the contents of temp back to the working directory
          mv temp/* .

          # Remove the temp directory
          rm -rf temp

          # Add all changes
          git add .

          # Commit the changes
          git commit -m "Update gh-pages with _site contents"

          # Push the changes to the gh-pages branch
          git push -u -f origin gh-pages
