name: Build Overbrowsing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all
jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/build/stopWorkflow.js

      - name: Set Stop Workflow Output
        id: set-stop-output
        run: echo "stopWorkflow=${{ steps.stop-check.outputs.stopWorkflow }}" > stopWorkflow.env

      - name: Set Stop Workflow Environment Variable
        run: echo "STOP_WORKFLOW=$(cat stopWorkflow.env)" >> $GITHUB_ENV

      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          yarn install
          yarn build

      - name: Deploy to gh-pages
        if: ${{ github.event_name == 'push' || env.STOP_WORKFLOW != 'true' }}
        run: |
          git checkout -b gh-pages

          # Create a temporary directory
          tmp_dir=$(mktemp -d)

          # Move the contents of _site to the temporary directory
          mv _site/* $tmp_dir

          # Remove all files and directories in the current directory
          rm -r *

          # Move the contents back to the current directory
          mv $tmp_dir/* .

          # Remove the temporary directory
          rmdir $tmp_dir

          git add .
          git commit -m "updating content"
          git push -f -u origin gh-pages
