name: Image Optimization and Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update -y && sudo apt-get install -y imagemagick

      - name: Run Yarn Build
        run: yarn build

      - name: Optimize and Convert to Black & White with Dithering
        run: |
          for file in uploads/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              extension="${filename##*.}"
              filename="${filename%.*}"
              output_file="uploads/$filename.png"
              convert "$file" -type Grayscale -ordered-dither h4x4a -quality 75% "$output_file"
            fi
          done

      - name: Commit and push optimized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add uploads
          git commit -m "Optimize and convert images to black and white with dithering"
          git push

      - name: Create or update gh-pages branch
        run: |
          if [[ $(git ls-remote --heads origin gh-pages) ]]; then
            git checkout gh-pages
            git merge origin/main --no-edit
          else
            git checkout -b gh-pages
          fi

          # Ensure the gh-pages branch contains only the optimized images
          git rm -r --ignore-unmatch '*'
          mv uploads/* .
          git add .
          git commit -m "Update gh-pages with optimized images"
          git push -u origin gh-pages
