name: Image Optimization and Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

permissions: write-all

jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflow should stop
        id: stop-check
        run: node scripts/build/stopWorkflow.js

      - name: Set Stop Workflow Output
        id: set-stop-output
        run: echo "stopWorkflow=${{ steps.stop-check.outputs.stopWorkflow }}" >> $GITHUB_ENV
        
      - name: Conditional workflow steps
        if: ${{ github.event_name == 'push' || steps.stop-check.outputs.stopWorkflow != 'true' }}
        run: |
          yarn install
          yarn build

          # Move into the _site directory
          cd _site

          # Initialize a new Git repository
          git init

          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

          # Add and commit all files
          git add .
          git commit -m "Deploy to GitHub Pages"

          # Force push to the gh-pages branch of your repository
          git push -f https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git master:gh-pages
